### PR TITLE
Lodash optimization

### PR DESCRIPTION
**Pull request by VadimKorobka**

### CODE REVIEW

**Comment by KorobkaVadim** [comment]
Babel-lodash plugin is not working expected. Please, use lodash modules. I tested it in my project by using webpack-bundle-analyzer.

**Comment by heartAndRain** [comment]
@JaKXz Can this PR be merged?

**Comment by MarcLopezAvila** [comment]
Please merge this PR, our bundle size is being affected.

**Comment by KorobkaVadim** [comment]
Dear @JaKXz,

To make a decision about PR, I propose to consider two aspects:

1. It is clear to everyone that these changes will not break anything.
2. This will really reduce the size of the bundle.
Hence, there is no reason to close PR. Even if you think that tree shaking works, then this change simply will not change anything. BUT if it is not true, then we will get a reduced bundle for many projects using this library. For example, many projects use Redux which depends on your library. We can merge this PR, and make a beta version, which everyone who needs it will try to switch to it, and a little later release a stable. 

I am looking forward for your reply.

Faithfully yours, Vadim

**Comment by andreieftimie** [comment]
Can we have this or something similar merged in?
This is pulling a complete lodash copy into our bundle.

**Comment by VadimKorobka** [comment]
Dear @JaKXz 
We are looking forward to your reply. If it's needed, I can answer the questions.

**Comment by luismesejo** [comment]
I beg you, please merge @timche

**Review by anmdotdev — APPROVED** [review]

**Comment by VadimKorobka** [comment]
Dear @JaKXz  & @timche 
We are looking forward to your reply. If it's needed, I can answer the questions.

**Comment by timche** [comment]
Thanks for your PR @VadimKorobka! Sorry that it took so long. I'm not actively maintaining this project anymore. I've created a new release.

**Pull request merged**
